### ISSUE TITLE
Update the version to 1.1 at UCSC Genome Browser on CHM13 ?

### ISSUE THREAD

**Issue by animesh** [marbl/CHM13-issues#3]
Thanks for this monumental work! Looks like it is v1 at http://genome.ucsc.edu/cgi-bin/hgTracks?db=hub_2395475_t2t-chm13-v1.0&lastVirtModeType=default&lastVirtModeExtraState=&virtModeType=default&virtMode=0&nonVirtPosition=&position=chr3%3A90755737%2D90789938&hgsid=1116564077_SGfUUmBADGIb8Vzqqk1VEwmZWELa  

Also, wondering about the availability of GFF for the same?

**Comment by skoren** [comment]
The genome browser will stay v1.0 for some time. The two assemblies are very similar, the main difference is the addition of the rDNA in v1.1 and some fixes in the telomere. If you're not looking at the rDNA/telomere, v1.0 should be equivalent. In the meantime, the CHM13 GitHub page has a liftover file from chm13 v1.0 to v1.1 in case you want to translate any data on the browser to v1.1: https://github.com/marbl/CHM13. There's also the gff for both v1.1 and v1.0 there.

**Comment by ValZapod** [comment]
Looks like it is available now. https://genome.ucsc.edu/cgi-bin/hgTracks?genome=t2t-chm13-v1.1&hubUrl=http://t2t.gi.ucsc.edu/chm13/hub/hub.txt
