### ISSUE TITLE
Further processing after alignment using Winnowmap

### ISSUE THREAD

**Issue by dKlee99** [marbl/CHM13-issues#4]
Which workflow / tools do you recommend to follow after aligning and filtering using Winnowmap? Should I follow standard minimap2 workflow after aligning? Thanks for your amazing works!

**Comment by dKlee99** [comment]
especially for variant calling, do you recommend using widely-used GATK Haplotype Caller? or sniffles for SV calling?

**Comment by arangrhie** [comment]
Hello @dKlee99 ,

Winnowmap outputs are almost interchangeable with minimap2, so I guess any SV or SNV calling would be compatible.
We have been using DeepVariant for the hybrid Illumina + HiFi dataset and ONT reads to call SNV-like errors and Sniffles for SV-like error detection (and determined true hets through manual evaluation). More details are detailed in our latest preprint [here](https://doi.org/10.1101/2021.07.02.450803), however we haven't compared to other variant callers. We picked those tools from the [PrecisionFDA Truth Challenge II](https://precision.fda.gov/challenges/10), but as you can see, there is no one-winner-for-all.

Arang
