### ISSUE TITLE
CHM13.GFF3.V4 annotations cause the phase error in bcftools

### ISSUE THREAD

**Issue by dKlee99** [marbl/CHM13-issues#5]
Hello,

I have issues with gff annotation using bcftools. At first, I used the following command 
`bcftools csq -f chm13_grch38_Y_added.fa -g chm13.draft_v1.1.gene_annotation.v4.gff3 ../longread/samtools/T15/T15_chm13_sorted.vcf -O z -o T15_chm13_sorted_annotated.vcf`
then got the error message saying `Could not parse the line, "Parent=transcript:" not present` so I adjusted gff file using `zcat chm13.draft_v1.1.gene_annotation.v4.gff3.gz \
    | gawk 'BEGIN{IGNORECASE=0} $0 ~/^#/ || ($3 != "gene" && $3 != "transcript" ) { $0=gensub(/Parent=(.+?_T[^;]+)/, "Parent=transcript:\\1", "g", $0); print; next} $0 !~/^#/ { gsub(/ID=/, "ID="$3":"); $0=gensub(/Parent=(.+?_G[^;]+)/, "Parent=gene:\\1", "g", $0);  print }' \
    | bgzip -c > chm13.draft_v1.1.gene_annotation.v4.fix.gff3.gz
` to fix the error message. 
But then I still get the phase error message
`Error: GFF3 assumption failed for transcript CHM13_T0000003, CDS=111940: phase!=len%3 (phase=2, len=379)`
and got the following message after --force running it.
`Warning: GFF3 assumption failed for transcript CHM13_T0110841, CDS=23883573: phase!=len%3 (phase=0, len=607)`
If bcftools seems to cause phase errors which tool do you recommend to use to annotate variant calls on CHM13? 

Seems like others are experiencing the same issue here
 
https://github.com/marbl/CHM13/issues/31 

Cheers, 
DK

**Comment by arangrhie** [comment]
Hello @dKlee99, I see a similar conversation is happening [here](https://github.com/marbl/CHM13/issues/31). Let's move this thread over there.
