### ISSUE TITLE
Validate that new 115 proteins are real using Alphafold-multimer and ColabFold

### ISSUE THREAD

**Issue by ValZapod** [marbl/CHM13-issues#6]
As said. Alphafold db is here https://alphafold.ebi.ac.uk/ and contains ALL proteins between 16 and 2700 aa. The others are available for humans in batch file in downloads.

**Comment by ValZapod** [comment]
Just FYI what Alphafold can do. https://www.science.org/doi/10.1126/science.abm4805

**Comment by ValZapod** [comment]
So... Did anyone press watch on the repository?

**Comment by aphillippy** [comment]
Hi @ValZapod , this repo is for tracking specific issues with the sequence assembly--not the annotation. We did provide a draft gene annotation in the associated paper, but the follow-on work to investigate and thoroughly annotate the newly assembled regions is outside the scope of this repo/project. If you're interested in helping, you might want to reach out to the GENCODE team https://www.gencodegenes.org/

**Comment by ValZapod** [comment]
Well, what meant you can use 2 or 3 proteins to show in the paper. That is like 1 hour or two in the cloud with alphafold. It will increase visability of your paper since alphafold is most important topic right now.

> interested in helping, you might want to reach out to the GENCODE team

Well, **naming** proteins is not that interesting.
